version: '3.7'

services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
